// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v3.20.0
// source: update.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Network, networkFromJSON, networkToJSON } from "./sologenic/com-fs-utils-lib/models/metadata/metadata";

export const protobufPackage = "update";

export enum Action {
  SUBSCRIBE = 0,
  UNSUBSCRIBE = 1,
  CLOSE = 2,
  RESPONSE = 3,
  PING = 4,
  UNRECOGNIZED = -1,
}

export function actionFromJSON(object: any): Action {
  switch (object) {
    case 0:
    case "SUBSCRIBE":
      return Action.SUBSCRIBE;
    case 1:
    case "UNSUBSCRIBE":
      return Action.UNSUBSCRIBE;
    case 2:
    case "CLOSE":
      return Action.CLOSE;
    case 3:
    case "RESPONSE":
      return Action.RESPONSE;
    case 4:
    case "PING":
      return Action.PING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Action.UNRECOGNIZED;
  }
}

export function actionToJSON(object: Action): string {
  switch (object) {
    case Action.SUBSCRIBE:
      return "SUBSCRIBE";
    case Action.UNSUBSCRIBE:
      return "UNSUBSCRIBE";
    case Action.CLOSE:
      return "CLOSE";
    case Action.RESPONSE:
      return "RESPONSE";
    case Action.PING:
      return "PING";
    case Action.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Method {
  /** NOT_USED - Left unused on purpose */
  NOT_USED = 0,
  /** NOTIFICATION - Represents a new notification (requires no ID in the subscription, returns no ID in the message) */
  NOTIFICATION = 1,
  NEW_KYC_STUCK = 2,
  /** AED - ID: {currency1}_{currency2}_{interval} (e.g. wusd_1_appl_1_30m) */
  AED = 3,
  UNRECOGNIZED = -1,
}

export function methodFromJSON(object: any): Method {
  switch (object) {
    case 0:
    case "NOT_USED":
      return Method.NOT_USED;
    case 1:
    case "NOTIFICATION":
      return Method.NOTIFICATION;
    case 2:
    case "NEW_KYC_STUCK":
      return Method.NEW_KYC_STUCK;
    case 3:
    case "AED":
      return Method.AED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Method.UNRECOGNIZED;
  }
}

export function methodToJSON(object: Method): string {
  switch (object) {
    case Method.NOT_USED:
      return "NOT_USED";
    case Method.NOTIFICATION:
      return "NOTIFICATION";
    case Method.NEW_KYC_STUCK:
      return "NEW_KYC_STUCK";
    case Method.AED:
      return "AED";
    case Method.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Subscribe {
  Action: Action;
  Subscription: Subscription | undefined;
}

export interface Subscription {
  Method: Method;
  ID: string;
  Network: Network;
  OrganizationID: string;
  Content?: string | undefined;
}

function createBaseSubscribe(): Subscribe {
  return { Action: 0, Subscription: undefined };
}

export const Subscribe = {
  encode(message: Subscribe, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Action !== 0) {
      writer.uint32(8).int32(message.Action);
    }
    if (message.Subscription !== undefined) {
      Subscription.encode(message.Subscription, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Subscribe {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Action = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Subscription = Subscription.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Subscribe {
    return {
      Action: isSet(object.Action) ? actionFromJSON(object.Action) : 0,
      Subscription: isSet(object.Subscription) ? Subscription.fromJSON(object.Subscription) : undefined,
    };
  },

  toJSON(message: Subscribe): unknown {
    const obj: any = {};
    if (message.Action !== 0) {
      obj.Action = actionToJSON(message.Action);
    }
    if (message.Subscription !== undefined) {
      obj.Subscription = Subscription.toJSON(message.Subscription);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Subscribe>, I>>(base?: I): Subscribe {
    return Subscribe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Subscribe>, I>>(object: I): Subscribe {
    const message = createBaseSubscribe();
    message.Action = object.Action ?? 0;
    message.Subscription = (object.Subscription !== undefined && object.Subscription !== null)
      ? Subscription.fromPartial(object.Subscription)
      : undefined;
    return message;
  },
};

function createBaseSubscription(): Subscription {
  return { Method: 0, ID: "", Network: 0, OrganizationID: "", Content: undefined };
}

export const Subscription = {
  encode(message: Subscription, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Method !== 0) {
      writer.uint32(8).int32(message.Method);
    }
    if (message.ID !== "") {
      writer.uint32(18).string(message.ID);
    }
    if (message.Network !== 0) {
      writer.uint32(24).int32(message.Network);
    }
    if (message.OrganizationID !== "") {
      writer.uint32(34).string(message.OrganizationID);
    }
    if (message.Content !== undefined) {
      writer.uint32(42).string(message.Content);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Subscription {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Method = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.Network = reader.int32() as any;
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.OrganizationID = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.Content = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Subscription {
    return {
      Method: isSet(object.Method) ? methodFromJSON(object.Method) : 0,
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      Network: isSet(object.Network) ? networkFromJSON(object.Network) : 0,
      OrganizationID: isSet(object.OrganizationID) ? globalThis.String(object.OrganizationID) : "",
      Content: isSet(object.Content) ? globalThis.String(object.Content) : undefined,
    };
  },

  toJSON(message: Subscription): unknown {
    const obj: any = {};
    if (message.Method !== 0) {
      obj.Method = methodToJSON(message.Method);
    }
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.Network !== 0) {
      obj.Network = networkToJSON(message.Network);
    }
    if (message.OrganizationID !== "") {
      obj.OrganizationID = message.OrganizationID;
    }
    if (message.Content !== undefined) {
      obj.Content = message.Content;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Subscription>, I>>(base?: I): Subscription {
    return Subscription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Subscription>, I>>(object: I): Subscription {
    const message = createBaseSubscription();
    message.Method = object.Method ?? 0;
    message.ID = object.ID ?? "";
    message.Network = object.Network ?? 0;
    message.OrganizationID = object.OrganizationID ?? "";
    message.Content = object.Content ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
