syntax = "proto3";

package update;

option go_package = "github.com/sologenic/com-fs-update-model;update";

import "sologenic/com-fs-utils-lib/models/metadata/metadata.proto";

message Subscribe {
    Action Action = 1;
    Subscription Subscription = 2;
}

message Subscription {
    Method Method = 1;
    string ID = 2;
    metadata.Network Network = 3;
    string OrganizationID = 4;
    optional string Content = 5;
}

enum Action {
    SUBSCRIBE = 0;
    UNSUBSCRIBE = 1;
    CLOSE = 2;
    RESPONSE = 3;
    PING = 4;
}

enum Method {
    NOT_USED = 0; // Left unused on purpose
    NOTIFICATION = 1; // Represents a new notification (requires no ID in the subscription, returns no ID in the message)
    NEW_KYC_STUCK = 2;
    AED = 3; // ID: {currency1}_{currency2}_{interval} (e.g. wusd_1_appl_1_30m)
    ALPACA_FEED = 4;
    SIGNING = 5;
}
