// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.0
//   protoc               v4.24.3
// source: update.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";

export const protobufPackage = "update";

export enum Action {
  SUBSCRIBE = 0,
  UNSUBSCRIBE = 1,
  CLOSE = 2,
  RESPONSE = 3,
  PING = 4,
  UNRECOGNIZED = -1,
}

export function actionFromJSON(object: any): Action {
  switch (object) {
    case 0:
    case "SUBSCRIBE":
      return Action.SUBSCRIBE;
    case 1:
    case "UNSUBSCRIBE":
      return Action.UNSUBSCRIBE;
    case 2:
    case "CLOSE":
      return Action.CLOSE;
    case 3:
    case "RESPONSE":
      return Action.RESPONSE;
    case 4:
    case "PING":
      return Action.PING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Action.UNRECOGNIZED;
  }
}

export function actionToJSON(object: Action): string {
  switch (object) {
    case Action.SUBSCRIBE:
      return "SUBSCRIBE";
    case Action.UNSUBSCRIBE:
      return "UNSUBSCRIBE";
    case Action.CLOSE:
      return "CLOSE";
    case Action.RESPONSE:
      return "RESPONSE";
    case Action.PING:
      return "PING";
    case Action.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Method {
  /** NOT_USED - Left unused on purpose */
  NOT_USED = 0,
  /** POOL - Represents an update to a pool (requires pool id in the subscription and contains pool ID in the message) */
  POOL = 1,
  /** NEW_POOL - Fired if a new pool is created. Contains the pool ID */
  NEW_POOL = 2,
  /** PRICE_VOLUME - Represents an update to a pool price volume chart (requires pool id in the subscription and contains pool ID in the message) */
  PRICE_VOLUME = 3,
  /** TRADES_FOR_ACCOUNT - Represents an update to trades for an account (requires account id in the subscription, returns pool id in the message) */
  TRADES_FOR_ACCOUNT = 4,
  /** LIQUIDITY_VOLUME_FEE - Represents an update to all pool liquidity, volume and fee (requires no ID in the subscription, returns no ID in the message) */
  LIQUIDITY_VOLUME_FEE = 5,
  /** NOTIFICATION - Represents a new notification (requires no ID in the subscription, returns no ID in the message) */
  NOTIFICATION = 6,
  UNRECOGNIZED = -1,
}

export function methodFromJSON(object: any): Method {
  switch (object) {
    case 0:
    case "NOT_USED":
      return Method.NOT_USED;
    case 1:
    case "POOL":
      return Method.POOL;
    case 2:
    case "NEW_POOL":
      return Method.NEW_POOL;
    case 3:
    case "PRICE_VOLUME":
      return Method.PRICE_VOLUME;
    case 4:
    case "TRADES_FOR_ACCOUNT":
      return Method.TRADES_FOR_ACCOUNT;
    case 5:
    case "LIQUIDITY_VOLUME_FEE":
      return Method.LIQUIDITY_VOLUME_FEE;
    case 6:
    case "NOTIFICATION":
      return Method.NOTIFICATION;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Method.UNRECOGNIZED;
  }
}

export function methodToJSON(object: Method): string {
  switch (object) {
    case Method.NOT_USED:
      return "NOT_USED";
    case Method.POOL:
      return "POOL";
    case Method.NEW_POOL:
      return "NEW_POOL";
    case Method.PRICE_VOLUME:
      return "PRICE_VOLUME";
    case Method.TRADES_FOR_ACCOUNT:
      return "TRADES_FOR_ACCOUNT";
    case Method.LIQUIDITY_VOLUME_FEE:
      return "LIQUIDITY_VOLUME_FEE";
    case Method.NOTIFICATION:
      return "NOTIFICATION";
    case Method.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Subscribe {
  Action: Action;
  Subscription: Subscription | undefined;
}

export interface Subscription {
  Method: Method;
  ID: string;
  Network: string;
}

function createBaseSubscribe(): Subscribe {
  return { Action: 0, Subscription: undefined };
}

export const Subscribe = {
  encode(message: Subscribe, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Action !== 0) {
      writer.uint32(8).int32(message.Action);
    }
    if (message.Subscription !== undefined) {
      Subscription.encode(message.Subscription, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Subscribe {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.Action = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.Subscription = Subscription.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Subscribe {
    return {
      Action: isSet(object.Action) ? actionFromJSON(object.Action) : 0,
      Subscription: isSet(object.Subscription) ? Subscription.fromJSON(object.Subscription) : undefined,
    };
  },

  toJSON(message: Subscribe): unknown {
    const obj: any = {};
    if (message.Action !== 0) {
      obj.Action = actionToJSON(message.Action);
    }
    if (message.Subscription !== undefined) {
      obj.Subscription = Subscription.toJSON(message.Subscription);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Subscribe>, I>>(base?: I): Subscribe {
    return Subscribe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Subscribe>, I>>(object: I): Subscribe {
    const message = createBaseSubscribe();
    message.Action = object.Action ?? 0;
    message.Subscription = (object.Subscription !== undefined && object.Subscription !== null)
      ? Subscription.fromPartial(object.Subscription)
      : undefined;
    return message;
  },
};

function createBaseSubscription(): Subscription {
  return { Method: 0, ID: "", Network: "" };
}

export const Subscription = {
  encode(message: Subscription, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.Method !== 0) {
      writer.uint32(16).int32(message.Method);
    }
    if (message.ID !== "") {
      writer.uint32(26).string(message.ID);
    }
    if (message.Network !== "") {
      writer.uint32(34).string(message.Network);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Subscription {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2:
          if (tag !== 16) {
            break;
          }

          message.Method = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.ID = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.Network = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Subscription {
    return {
      Method: isSet(object.Method) ? methodFromJSON(object.Method) : 0,
      ID: isSet(object.ID) ? globalThis.String(object.ID) : "",
      Network: isSet(object.Network) ? globalThis.String(object.Network) : "",
    };
  },

  toJSON(message: Subscription): unknown {
    const obj: any = {};
    if (message.Method !== 0) {
      obj.Method = methodToJSON(message.Method);
    }
    if (message.ID !== "") {
      obj.ID = message.ID;
    }
    if (message.Network !== "") {
      obj.Network = message.Network;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Subscription>, I>>(base?: I): Subscription {
    return Subscription.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Subscription>, I>>(object: I): Subscription {
    const message = createBaseSubscription();
    message.Method = object.Method ?? 0;
    message.ID = object.ID ?? "";
    message.Network = object.Network ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
