syntax = "proto3";

package update;

option go_package = "github.com/sologenic/fs-update-model;update";

message Subscribe {
    Action Action = 1;
    Subscription Subscription = 2;
}

message Subscription {
    Method Method = 2;
    string ID = 3;
    string Network = 4;
}

enum Action {
    SUBSCRIBE = 0;
    UNSUBSCRIBE = 1;
    CLOSE = 2;
    RESPONSE = 3;
    PING = 4;
}

enum Method {
    NOT_USED = 0; // Left unused on purpose
    NOTIFICATION = 1; // Represents a new notification (requires no ID in the subscription, returns no ID in the message)
    NEW_KYC_STUCK = 2;
}
