// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: update.proto

package update

import (
	metadata "github.com/sologenic/com-fs-utils-lib/models/metadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_SUBSCRIBE   Action = 0
	Action_UNSUBSCRIBE Action = 1
	Action_CLOSE       Action = 2
	Action_RESPONSE    Action = 3
	Action_PING        Action = 4
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "SUBSCRIBE",
		1: "UNSUBSCRIBE",
		2: "CLOSE",
		3: "RESPONSE",
		4: "PING",
	}
	Action_value = map[string]int32{
		"SUBSCRIBE":   0,
		"UNSUBSCRIBE": 1,
		"CLOSE":       2,
		"RESPONSE":    3,
		"PING":        4,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_update_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_update_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{0}
}

type Method int32

const (
	Method_NOT_USED      Method = 0 // Left unused on purpose
	Method_NOTIFICATION  Method = 1 // Represents a new notification (requires no ID in the subscription, returns no ID in the message)
	Method_NEW_KYC_STUCK Method = 2
	Method_AED           Method = 3 // ID: {currency1}_{currency2}_{interval} (e.g. wusd_1_appl_1_30m)
	Method_ALPACA_FEED   Method = 4
	Method_SIGNING       Method = 5
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "NOT_USED",
		1: "NOTIFICATION",
		2: "NEW_KYC_STUCK",
		3: "AED",
		4: "ALPACA_FEED",
		5: "SIGNING",
	}
	Method_value = map[string]int32{
		"NOT_USED":      0,
		"NOTIFICATION":  1,
		"NEW_KYC_STUCK": 2,
		"AED":           3,
		"ALPACA_FEED":   4,
		"SIGNING":       5,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_update_proto_enumTypes[1].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_update_proto_enumTypes[1]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{1}
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=Action,proto3,enum=update.Action" json:"Action,omitempty"`
	Subscription  *Subscription          `protobuf:"bytes,2,opt,name=Subscription,proto3" json:"Subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_SUBSCRIBE
}

func (x *Subscribe) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type Subscription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Method         Method                 `protobuf:"varint,1,opt,name=Method,proto3,enum=update.Method" json:"Method,omitempty"`
	ID             string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Network        metadata.Network       `protobuf:"varint,3,opt,name=Network,proto3,enum=metadata.Network" json:"Network,omitempty"`
	OrganizationID string                 `protobuf:"bytes,4,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	Content        *string                `protobuf:"bytes,5,opt,name=Content,proto3,oneof" json:"Content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_NOT_USED
}

func (x *Subscription) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Subscription) GetNetwork() metadata.Network {
	if x != nil {
		return x.Network
	}
	return metadata.Network(0)
}

func (x *Subscription) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

func (x *Subscription) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

var File_update_proto protoreflect.FileDescriptor

const file_update_proto_rawDesc = "" +
	"\n" +
	"\fupdate.proto\x12\x06update\x1a9sologenic/com-fs-utils-lib/models/metadata/metadata.proto\"m\n" +
	"\tSubscribe\x12&\n" +
	"\x06Action\x18\x01 \x01(\x0e2\x0e.update.ActionR\x06Action\x128\n" +
	"\fSubscription\x18\x02 \x01(\v2\x14.update.SubscriptionR\fSubscription\"\xc6\x01\n" +
	"\fSubscription\x12&\n" +
	"\x06Method\x18\x01 \x01(\x0e2\x0e.update.MethodR\x06Method\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\x12+\n" +
	"\aNetwork\x18\x03 \x01(\x0e2\x11.metadata.NetworkR\aNetwork\x12&\n" +
	"\x0eOrganizationID\x18\x04 \x01(\tR\x0eOrganizationID\x12\x1d\n" +
	"\aContent\x18\x05 \x01(\tH\x00R\aContent\x88\x01\x01B\n" +
	"\n" +
	"\b_Content*K\n" +
	"\x06Action\x12\r\n" +
	"\tSUBSCRIBE\x10\x00\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x01\x12\t\n" +
	"\x05CLOSE\x10\x02\x12\f\n" +
	"\bRESPONSE\x10\x03\x12\b\n" +
	"\x04PING\x10\x04*b\n" +
	"\x06Method\x12\f\n" +
	"\bNOT_USED\x10\x00\x12\x10\n" +
	"\fNOTIFICATION\x10\x01\x12\x11\n" +
	"\rNEW_KYC_STUCK\x10\x02\x12\a\n" +
	"\x03AED\x10\x03\x12\x0f\n" +
	"\vALPACA_FEED\x10\x04\x12\v\n" +
	"\aSIGNING\x10\x05B1Z/github.com/sologenic/com-fs-update-model;updateb\x06proto3"

var (
	file_update_proto_rawDescOnce sync.Once
	file_update_proto_rawDescData []byte
)

func file_update_proto_rawDescGZIP() []byte {
	file_update_proto_rawDescOnce.Do(func() {
		file_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_proto_rawDesc), len(file_update_proto_rawDesc)))
	})
	return file_update_proto_rawDescData
}

var file_update_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_update_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_update_proto_goTypes = []any{
	(Action)(0),           // 0: update.Action
	(Method)(0),           // 1: update.Method
	(*Subscribe)(nil),     // 2: update.Subscribe
	(*Subscription)(nil),  // 3: update.Subscription
	(metadata.Network)(0), // 4: metadata.Network
}
var file_update_proto_depIdxs = []int32{
	0, // 0: update.Subscribe.Action:type_name -> update.Action
	3, // 1: update.Subscribe.Subscription:type_name -> update.Subscription
	1, // 2: update.Subscription.Method:type_name -> update.Method
	4, // 3: update.Subscription.Network:type_name -> metadata.Network
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_update_proto_init() }
func file_update_proto_init() {
	if File_update_proto != nil {
		return
	}
	file_update_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_proto_rawDesc), len(file_update_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_update_proto_goTypes,
		DependencyIndexes: file_update_proto_depIdxs,
		EnumInfos:         file_update_proto_enumTypes,
		MessageInfos:      file_update_proto_msgTypes,
	}.Build()
	File_update_proto = out.File
	file_update_proto_goTypes = nil
	file_update_proto_depIdxs = nil
}
